config/routes.rb
Rails.application.routes.draw do

  resources :contacts
root to: 'pages#index'

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Your message successfully submit.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message, :phone)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  	 @contact = Contact.new
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th >Name</th>
      <th >Email </th>
      <th >Phone </th>
      <th >Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<header id="homee">
			<div class="container">
				<div class="top-bar">
					<ul class="con-links">
						<li><span>+91 8015106497</span></li>
						<li><span>hello@shopknekt.com</span></li>
					</ul>
					<!-- <div class="search-bar">
						<form>
							<input type="text" name="search" placeholder="Search">
							<button type="submit"><img src="http://creativethemes.us/helix/images/search.png" alt=""></button>
						</form>
					</div> -->
				</div>
				<div class="bt-header"></div>
				<div class="bottom-header one hmee">
					<div class="container">
						<div class="logo">
							<a href="index.html" title="">
							<img src="<%= asset_url('Logo.png') %>" alt="" class= "z-img img-responsive" />	
							</a>
						</div><!--logo end-->
						<nav>
							<ul>
								<li><a href="#homee" title="">Home</a>
								</li>
								<li><a href="#servicess" title="">Services</a></li>
								<li><a href="#aboutt" title="">About us</a></li>
								<!-- <li><a href="#workk" title="">Work</a></li> -->
								<!-- <li><a href="#teamm" title="">Team</a></li> -->
								<li><a href="#contactt" title="">Contact</a></li>
							</ul>
						</nav><!--nav end-->
						<div class="menu-icon">
							<img class="op" src="http://creativethemes.us/helix/images/menu-bar.png" alt="">
							<img class="crs" src="http://creativethemes.us/helix/images/cross.png" alt="">
						</div><!--menu-icon end-->
					</div>
				</div>
			</div>
		</header><!-- Header end-->	

		<div class="responsive-mobile-menu">
			<div class="reponsive-menu">
				<ul>
					<li><a href="#homee" title="">Home <span class="caret"></span></a>
					</li>
					<li><a href="#servicess" title="">Features</a></li>
					<li><a href="#aboutt" title="">About Us</a></li>
					<!-- <li><a href="#workk" title="">Work</a></li> -->
					<!-- <li><a href="#teamm" title="">Team</a></li> -->
					<li><a href="#" title="">Pages <span class="caret"></span></a>
						<ul>
							<li><a class="external" href="blogs.html" title="">Blog</a></li>
							<li><a class="external" href="blog-details.html" title="">Blog Details</a></li>
							<li><a class="external" href="comingsoon2.html" title="">Coming Soon</a></li>
							<li><a class="external" href="error.html" title="">Error 404</a></li>
						</ul>
					</li>
					<li><a href="#contactt" title="">Contact</a></li>
				</ul>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Zadp Solution</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag "application", media: 'all', "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
	<div class="wrapper">
  <%= render 'layouts/navbar' %>
	<%= yield %>
	</div>
</body>
</html>

app/views/message/contact_me.html.erb
<h1>Message#contact_me</h1>

<p>
  <%= @greeting %>, find me in app/views/message/contact_me.html.erb
</p>

app/views/message/contact_me.text.erb
Message#contact_me

<%= @greeting %>, find me in app/views/message/contact_me.text.erb
<%= @body %>

app/views/messages/new.html.erb
<%= form_for @message, url: create_message_url do |f| %>
  <%= notice %>
  <%= @message.errors.full_messages.join(', ') %>

  <%= f.text_field :name, placeholder: 'name' %>
  <%= f.email_field :email, placeholder: 'email' %>
  <%= f.text_area :body, placeholder: 'body' %>
  <%= f.submit 'Send' %>
<% end %>